baseURL = 'https://serverx.org.in/'
languageCode = 'en-us'
title = 'SERVER-X-101'
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS"]


[params]
mainSections = ["articles", "snippets", "authors", "contests"]


[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

preserveTaxonomyNames = true  